// @ts-check
/**
 * Bundle the official Anthropic SDK into one browser file for the extension's
 * "direct" mode:  extension/vendor/anthropic-sdk.mjs
 *
 *   npm run vendor:sdk
 *
 * Why a vendored file: the extension has no build step, and the SDK package is
 * written for bundlers (its entry point also imports Node-only helpers). This is
 * the only bundled file; run it again after upgrading @anthropic-ai/sdk.
 */

import { build } from 'esbuild';
import { copyFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const sdk = JSON.parse(readFileSync(`${root}/node_modules/@anthropic-ai/sdk/package.json`, 'utf8'));

await build({
  entryPoints: [`${root}/node_modules/@anthropic-ai/sdk/index.mjs`],
  outfile: `${root}/extension/vendor/anthropic-sdk.mjs`,
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'chrome116',
  // Readable (not obfuscated) for Chrome Web Store review: whitespace/syntax minification only.
  minifyWhitespace: true,
  minifySyntax: true,
  legalComments: 'eof',
  banner: {
    js: `// Vendored @anthropic-ai/sdk ${sdk.version} (${sdk.license}) for the extension's direct mode.\n// Generated by scripts/vendor-sdk.js; do not edit. Source: https://github.com/anthropics/anthropic-sdk-typescript`,
  },
  logLevel: 'info',
});

// The SDK's MIT license asks for its notice to ship with every copy: next to the bundle.
copyFileSync(`${root}/node_modules/@anthropic-ai/sdk/LICENSE`, `${root}/extension/vendor/anthropic-sdk-LICENSE.txt`);
